### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by EdoaLive** [skeyby/mysqlfs#6]
Hi!
My interest is growing on a solutions that put a filesystem inside a mysql (mariadb) database. Mainly because of the new (not quite) feature of Galera clustering.
My question is: what is the status of this project? Is it considered stable (at some point)? Do you know any (newer?) alternatives?

Thank you!

**Comment by skeyby** [comment]
Hi.

The project is quite stable. We've been using it for years in production handling quite big amount of datas (TBs).

**Comment by Edwin-Edward** [comment]
Thank you! 
I'm going to create and maintain an ebuild for Gentoo distribution.
What is the source of the latest stable release? There's a source package?
Or I should just get a copy of a specified git branch/tag?

**Comment by skeyby** [comment]
I'd go with the "TEST" branch, but if you give me a couple of days I can freeze a stable 1.0 version. I think it's definitely time to.

**Comment by Edwin-Edward** [comment]
Is there some news about version 1.0?

Thanks!

**Comment by skeyby** [comment]
> Is there any news about version 1.0?
> 
> Thanks!

Better late than never.

Testing and packaging it.

I hope to release it tomorrow.
